### ISSUE TITLE
DB 환경 변수 생성 및 필요한 라이브러리 설치

### ISSUE THREAD

**Issue by SSUK-H** [SSUK-H/SSAP-IDE-Backend-Chat#11]
## 작업 사항

> 데이터베이스 연결 정보는 환경 변수를 사용하여 관리하기 위해 .env 파일을 생성하여 데이터베이스 정보를 저장과 필요한 라이브러리 설치 했습니다.

## To-do
- [x] .env 파일을 생성하여 데이터베이스 정보를 저장
- 필요한 라이브러리 설치
   - [x] dotenv: 환경 변수 설정을 위한 패키지 로드 설치 #11
   - [x] express-session: #17
   - [x] express-socket.io-session: #17
