### ISSUE TITLE
소켓 접속자 인증 및 설정, 메세지 DB저장 수정, 연결 종료 처리 추가

### ISSUE THREAD

**Issue by SSUK-H** [SSUK-H/SSAP-IDE-Backend-Chat#14]
## 작업 사항

> setUserInfo로 클라이언트에서 보낸 email과 name을 받아 접속자 확인을 진행하고 joinTime 이후 채팅 데이터 불러오는 로직은 나중에 session 로직에서  따로 처리하기 위해 삭제하고 email 데이터를 받아와서 방에 입장한 사용자를 확인했습니다. sendMessage에서 채팅 데이터 받아 DB 저장하는 saveMessageToDB 호출해서 저장하도록 수정하였으며, 연결 종료 시 처리하는 로직을 추가하였습니다.

## To-do
- [x] 소켓 접속자 인증 및 설정
- [x] 메세지 DB저장 수정
- [x] 연결 종료 처리 추가
- [x] #16
