### ISSUE TITLE
채팅 메세지 유지를 위한 session 로직 추가

### ISSUE THREAD

**Issue by SSUK-H** [SSUK-H/SSAP-IDE-Backend-Chat#17]
## 작업 사항

> express-session 미들웨어를 사용해서 세션 데이터는 crypto로 랜덤 문자열을 생성해 secret를 암호화하고 세션 데이터 변경 시 저장하지 않게 resave를 설정했으며, 초기화 되지 않는 데이터는 저장되지 않도록 saveUninitialized를 설정했습니다. 그리고 클라이언트로부터 요청이 들어오면 header에서 email과 name을 세션에 저장하고 소켓 연결 시 세션에 사용자 정보와 첫 접속 시간을 체크해 세션에 저장합니다. 세션에 저장된 사용자 정보 확인 후 첫 접속 시간 이후 채팅 내용들을 DB에서 조회하도록 하였습니다.

## To-do
- [x] express-session을 사용해서 세션설정
- [x] 소켓 연결 시 세션에 사용자 정보 저장
- [x] 세션에 저장된 사용자 정보 확인 후 DB에서 채팅 내용 조회
- [x] #19

## 기타사항

> 기타 사항을 작성해주세요
