### ISSUE TITLE
DB 연동 및 AWS 배포

### ISSUE THREAD

**Issue by SSUK-H** [SSUK-H/SSAP-IDE-Backend-Chat#5]
## 작업 사항

> node.js로 MySQL를 사용하므로 mysql2 패키지를 설치하고 서버쪽에서 DB환경변수 설정하였습니다. 그리고 클라이언트에서 받은 채팅 데이터를 DB에 저장하였습니다.

## To-do
- [x] MySQL 패키지 설치
`npm install mysql2`
- [x] DB 환경변수 설정 및 연결
- [x] 클라이언트에서 받은 채팅 데이터 저장하기
- [ ] #6
- [ ] Node.js 개발을 자동화 위해 nodemon 패키지 설치 및 설정
- [ ] #7
